Repository mockery/mockery, pull requests merged in 2023-08, with the labels that each got.

#1316 Fix compatibility issues with PHP 7.3
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/workflows/codecov.yml
  .github/workflows/psalm.yml
  .github/workflows/tests.yml
  Makefile
  composer.json
  composer.lock
  library/Mockery/Generator/DefinedTargetClass.php
  library/Mockery/Reflector.php
  phpunit.xml.dist
  psalm-baseline.xml
  psalm.xml.dist
  tests/Mockery/Matcher/SubsetTest.php
Labels: patch, dependencies, Fixed, Announcement

#1318 Fix misspelling in docs
  docs/reference/spies.rst
Labels: Documentation, patch

#1320 Clean up mocks on destruct
  library/Mockery/Loader/RequireLoader.php
Labels: patch, Refactor

#1321 Autoload Test Fixtures Based on PHP Runtime Version
  composer.json
  fixtures/autoload.php
  psalm-baseline.xml
Labels: patch, Chore

#1322 Changelog v1.6.5
  CHANGELOG.md
  psalm-baseline.xml
Labels: patch, Changelog, Chore

#1325 Keep the file that caused an error for inspection
  library/Mockery/Loader/RequireLoader.php
Labels: patch, Chore

#1324 Replace `+` Array Union Operator with `array_merge`
  library/Mockery/Reflector.php
Labels: patch, Fixed

#1327 Changelog v1.6.6
  CHANGELOG.md
Labels: patch, Changelog
