Repository mockery/mockery, pull requests merged in 2023-05, with the labels that each got.

#1246 Add `BUG_REPORT.yml` Issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: automation, patch

#1245 Deprecate `hamcrest/hamcrest-php` package
  CONTRIBUTING.md
  docs/getting_started/upgrading.rst
  library/Mockery/Configuration.php
  library/Mockery/Expectation.php
  library/Mockery/Matcher/MustBe.php
Labels: deprecation, patch

#1243 Changelog v1.6.0
  CHANGELOG.md
Labels: patch, changelog, Chore

#1249 Merge `1.6.x` into `2.0.x`
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  CONTRIBUTING.md
  composer.json
  docs/getting_started/upgrading.rst
  library/Mockery/Configuration.php
  library/Mockery/CountValidator/Exception.php
  library/Mockery/Exception.php
  library/Mockery/Exception/BadMethodCallException.php
  library/Mockery/Exception/InvalidArgumentException.php
  library/Mockery/Exception/MockeryExceptionInterface.php
  library/Mockery/Exception/RuntimeException.php
  library/Mockery/Expectation.php
  library/Mockery/Generator/DefinedTargetClass.php
  library/Mockery/Generator/StringManipulation/Pass/ClassAttributesPass.php
  library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
  library/Mockery/Generator/UndefinedTargetClass.php
  library/Mockery/Matcher/MustBe.php
  library/Mockery/Mock.php
  psalm-baseline.xml
  psalm.xml.dist
  tests/Mockery/Generator/StringManipulation/Pass/ClassAttributesPassTest.php
  tests/PHP81/Php81LanguageFeaturesTest.php
Labels: patch, Chore

#1227 Remove `hamcrest/hamcrest-php` package
  composer.json
  composer.lock
  library/Mockery/Configuration.php
  library/Mockery/Expectation.php
  psalm-baseline.xml
  tests/Bootstrap.php
  tests/Mockery/DefaultMatchersTest.php
  tests/Mockery/HamcrestExpectationTest.php
Labels: major, Removed

#1251 Update CHANGELOG.md
  CHANGELOG.md
Labels: changelog

#1253 Prevent array to string conversion in Subset matcher
  CHANGELOG.md
  library/Mockery/Matcher/Subset.php
  tests/Mockery/Matcher/SubsetTest.php
Labels: patch, Fixed

#1254 Merge branch `1.6.x` into `2.0.x`
  CHANGELOG.md
  library/Mockery/Matcher/Subset.php
  tests/Mockery/Matcher/SubsetTest.php
Labels: patch, Chore

#1256 Removed support for PHP 8.0 and lower
  .github/workflows/codecov.yml
  .github/workflows/psalm.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml.dist
Labels: automation, major, changelog, dependencies, Removed

#1257 Refactor `Generator` Interface and implementations
  library/Mockery/Generator/CachingGenerator.php
  library/Mockery/Generator/Generator.php
  library/Mockery/Generator/StringManipulationGenerator.php
  psalm-baseline.xml
Labels: major, Changed, Refactor, Chore

#1258 Refactor `Loader` Interface and implementations
  library/Mockery/Loader/EvalLoader.php
  library/Mockery/Loader/Loader.php
  library/Mockery/Loader/RequireLoader.php
  psalm-baseline.xml
Labels: major, Changed, Refactor, Chore

#1259 Refactor `CountValidator` implementation
  library/Mockery/CountValidator/AbstractCountValidator.php
  library/Mockery/CountValidator/AtLeast.php
  library/Mockery/CountValidator/AtMost.php
  library/Mockery/CountValidator/CountValidatorAbstract.php
  library/Mockery/CountValidator/Exact.php
  library/Mockery/CountValidator/Exception.php
  psalm-baseline.xml
Labels: major, Changed, Refactor, Chore

#1260 Refactor `Matcher` implementations
  library/Mockery.php
  library/Mockery/Configuration.php
  library/Mockery/Expectation.php
  library/Mockery/Matcher/AbstractMatcher.php
  library/Mockery/Matcher/AndAnyOtherArgs.php
  library/Mockery/Matcher/Any.php
  library/Mockery/Matcher/AnyArgs.php
  library/Mockery/Matcher/AnyOf.php
  library/Mockery/Matcher/ArgumentListMatcher.php
  library/Mockery/Matcher/Closure.php
  library/Mockery/Matcher/Contains.php
  library/Mockery/Matcher/Ducktype.php
  library/Mockery/Matcher/HasKey.php
  library/Mockery/Matcher/HasValue.php
  library/Mockery/Matcher/MatcherAbstract.php
  library/Mockery/Matcher/MultiArgumentClosure.php
  library/Mockery/Matcher/MustBe.php
  library/Mockery/Matcher/NoArgs.php
  library/Mockery/Matcher/Not.php
  library/Mockery/Matcher/NotAnyOf.php
  library/Mockery/Matcher/Pattern.php
  library/Mockery/Matcher/Subset.php
  library/Mockery/Matcher/Type.php
  psalm-baseline.xml
  tests/Mockery/DefaultMatchersTest.php
Labels: major, Changed, Refactor, Chore

#1262 Update branch alias for 1.6.x
  composer.json
Labels: waiting-for-feedback, patch, Chore
