Repository mockery/mockery, pull requests merged in 2023-07, with the labels that each got.

#1294 Correct return types of Mock for phpstan
  psalm-baseline.xml
  src/Mockery/LegacyMockInterface.php
  src/Mockery/Mock.php
Labels: patch, Awaiting Reply

#1296 Update makefile
  Makefile
Labels: patch, dependencies, Chore

#1297 Update `Makefile` for contributors
  Makefile
Labels: patch, dependencies, Chore

#1301 Fix mocking classes with `new` initializers in method and attribute params on PHP 8.1
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
  tests/Fixture/PHP81/A.php
  tests/Fixture/PHP81/B.php
  tests/Fixture/PHP81/C.php
  tests/Fixture/PHP81/HandlerClass.php
  tests/Fixture/PHP81/MockClass.php
  tests/Fixture/PHP81/SomeAttribute.php
  tests/Unit/PHP81/Php81LanguageFeaturesTest.php
Labels: Bug, patch, Fixed

#1304 Remove `extra.branch-alias` and update composer information
  composer.json
Labels: dependencies, Chore

#1302 Changelog v1.6.3
  CHANGELOG.md
Labels: patch, Changelog

#1305 Setup `symplify/easy-coding-standard`
  .gitattributes
  .gitignore
  .php-cs-fixer.dist.php
  .php_cs
  .styleci.yml
  composer.json
  composer.lock
  ecs.php
Labels: patch, dependencies, Chore

#1308 Changelog v1.6.4
  CHANGELOG.md
Labels: patch, Changelog, Fixed

#1299 Test PHP `8.3` language features
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Fixture/PHP83/ClassName.php
  tests/Fixture/PHP83/Classes.php
  tests/Fixture/PHP83/Enums.php
  tests/Fixture/PHP83/Interfaces.php
  tests/Fixture/PHP83/Traits.php
  tests/Mockery/RegExpCompatability.php
  tests/Unit/PHP83/Php83LanguageFeaturesTest.php
Labels: patch, Tests, Chore

#1312 Mock disjunctive normal form types
  composer.lock
  library/Mockery/Reflector.php
  phpunit.xml.dist
  psalm-baseline.xml
  tests/Bootstrap.php
  tests/Fixture/PHP82/A.php
  tests/Fixture/PHP82/B.php
  tests/Fixture/PHP82/C.php
  tests/Unit/PHP82/Php82LanguageFeaturesTest.php
Labels: patch, Fixed, Refactor

#1313 Type declaration for `iterable|object`
  library/Mockery/Reflector.php
  tests/Bootstrap.php
  tests/Mockery/ReflectorTest.php
  tests/Unit/PHP82/Php82LanguageFeaturesTest.php
Labels: patch, Fixed, Refactor

#1314 Add Security Policy
  SECURITY.md
Labels: patch, Chore
