Repository mockery/mockery, pull requests merged in 2023-11, with the labels that each got.

#1336 Add factory methods for `IsEqual` and `IsSame` matchers
  library/Mockery.php
  tests/Mockery/Matcher/IsEqualTest.php
  tests/Mockery/Matcher/IsSameTest.php
Labels: patch

#1338 Support PHPUnit constraints as matchers
  .github/workflows/codecov.yml
  .github/workflows/psalm.yml
  composer.json
  library/Mockery.php
  library/Mockery/Configuration.php
  library/Mockery/Expectation.php
  library/Mockery/Matcher/MatcherAbstract.php
  library/Mockery/Matcher/MatcherInterface.php
  phpunit.xml.dist
  psalm-baseline.xml
  tests/Mockery/Adapter/Phpunit/PhpUnitConstraintExpectationTest.php
  tests/Mockery/ContainerTest.php
  tests/Mockery/Generator/StringManipulation/Pass/ClassAttributesPassTest.php
  tests/Mockery/MockeryCanMockMultipleInterfacesWhichOverlapTest.php
  tests/Mockery/MockingNullableMethodsTest.php
  tests/Mockery/TraitsTest.php
  tests/Mockery/WithCustomFormatterExpectationTest.php
  tests/Mockery/WithFormatterExpectationTest.php
Labels: deprecation, enhancement, patch

#1340 docs: Remove misplaced semicolumn from code snippet
  docs/reference/expectations.rst
Labels: Documentation, patch

#1342 Add `.readthedocs.yml` configuration
  .readthedocs.yml
  docs/conf.py
  docs/reference/index.rst
  docs/requirements.txt
Labels: Documentation, patch

#1343 Update documentation default theme and build version
  docs/_static/.gitkeep
  docs/conf.py
Labels: Documentation, patch
