Repository mockery/mockery, pull requests merged in 2024-02, with the labels that each got.

#1354 Add array-like objects support to hasKey/hasValue matchers
  library/Mockery/Matcher/HasKey.php
  library/Mockery/Matcher/HasValue.php
  psalm-baseline.xml
  tests/Mockery/Matcher/HasKeyTest.php
  tests/Mockery/Matcher/HasValueTest.php
Labels: patch, Added

#1355 Fix the namespace in the SubsetTest class
  tests/Mockery/Matcher/SubsetTest.php
Labels: patch, Tests

#1360 Refactor Container
  library/Mockery/Container.php
  psalm-baseline.xml
Labels: Performance, Refactor

#1361 Refactor `library/Mockery.php`
  library/Mockery.php
  psalm-baseline.xml
Labels: Performance, Refactor

#1362 Refactor `library/Mockery/ClosureWrapper.php`
  library/Mockery/ClosureWrapper.php
Labels: Performance, Refactor

#1363 Refactor `library/Mockery/CompositeExpectation.php `
  library/Mockery/CompositeExpectation.php
Labels: Performance, Refactor

#1364 Refactor `library/Mockery/Configuration.php`
  library/Mockery/Configuration.php
Labels: Performance, Refactor

#1365 Refactor `library/Mockery/Container.php`
  library/Mockery/Container.php
Labels: Performance, Refactor

#1366 Refactor `library/Mockery/Exception.php`
  library/Mockery/Exception.php
Labels: Performance, Refactor

#1367 Refactor `library/Mockery/Expectation.php`
  library/Mockery/Expectation.php
Labels: Performance, Refactor

#1368 Refactor `library/Mockery/ExpectationDirector.php`
  library/Mockery/ExpectationDirector.php
Labels: Performance, Refactor

#1369 Refactor `library/Mockery/ExpectationInterface.php`
  library/Mockery/ExpectationInterface.php
Labels: Performance, Refactor

#1370 Refactor `library/Mockery/ExpectsHigherOrderMessage.php`
  library/Mockery/ExpectsHigherOrderMessage.php
Labels: Performance, Refactor

#1371 Refactor `library/Mockery/HigherOrderMessage.php `
  library/Mockery/HigherOrderMessage.php
Labels: Performance, Refactor

#1372 Refactor `library/Mockery/Instantiator.php`
  library/Mockery/Instantiator.php
Labels: Performance, Refactor

#1373 Refactor `library/Mockery/LegacyMockInterface.php`
  library/Mockery/LegacyMockInterface.php
Labels: Performance, Refactor

#1374 Refactor `library/Mockery/MethodCall.php `
  library/Mockery/MethodCall.php
Labels: Performance, Refactor

#1380 Refactor `library/Mockery/QuickDefinitionsConfiguration.php `
  library/Mockery/QuickDefinitionsConfiguration.php
Labels: Performance, Refactor

#1382 Refactor `library/Mockery/VerificationExpectation.php`
  library/Mockery/VerificationExpectation.php
Labels: Performance, Refactor

#1379 Refactor `library/Mockery/Undefined.php`
  library/Mockery/Undefined.php
Labels: Performance, Refactor

#1377 Refactor `library/Mockery/ReceivedMethodCalls.php`
  library/Mockery/ReceivedMethodCalls.php
Labels: Performance, Refactor

#1378 Refactor `library/Mockery/Reflector.php`
  library/Mockery/Reflector.php
Labels: Performance, Refactor

#1376 Refactor `library/Mockery.php`
  library/Mockery.php
Labels: Performance, Refactor

#1381 Refactor `library/Mockery/VerificationDirector.php`
  library/Mockery/VerificationDirector.php
Labels: Performance, Refactor

#1385 Update composer dependencies and clean up
  composer.json
  composer.lock
  library/Mockery.php
  library/Mockery/Configuration.php
  library/Mockery/Container.php
  library/Mockery/Instantiator.php
  library/Mockery/Reflector.php
Labels: patch, Chore
