Repository mockery/mockery, pull requests merged in 2024-03, with the labels that each got.

#1386 Add PHPUnit 10+ attributes
  library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php
Labels: patch, Chore

#1391 chore: fix ci deprecations
  .github/workflows/codecov.yml
  .github/workflows/psalm.yml
  .github/workflows/tests.yml
Labels: Automation, Chore

#1389 Refactor `library/Mockery/Matcher/*`
  library/Mockery/Matcher/AndAnyOtherArgs.php
  library/Mockery/Matcher/Any.php
  library/Mockery/Matcher/AnyArgs.php
  library/Mockery/Matcher/AnyOf.php
  library/Mockery/Matcher/ArgumentListMatcher.php
  library/Mockery/Matcher/Closure.php
  library/Mockery/Matcher/Contains.php
  library/Mockery/Matcher/Ducktype.php
  library/Mockery/Matcher/HasKey.php
  library/Mockery/Matcher/HasValue.php
  library/Mockery/Matcher/IsEqual.php
  library/Mockery/Matcher/IsSame.php
  library/Mockery/Matcher/MatcherAbstract.php
  library/Mockery/Matcher/MatcherInterface.php
  library/Mockery/Matcher/MultiArgumentClosure.php
  library/Mockery/Matcher/MustBe.php
  library/Mockery/Matcher/NoArgs.php
  library/Mockery/Matcher/Not.php
  library/Mockery/Matcher/NotAnyOf.php
  library/Mockery/Matcher/Pattern.php
  library/Mockery/Matcher/Subset.php
  library/Mockery/Matcher/Type.php
Labels: Performance, Refactor

#1388 Refactor `library/Mockery/Loader/*`
  library/Mockery/Loader/EvalLoader.php
  library/Mockery/Loader/Loader.php
  library/Mockery/Loader/RequireLoader.php
Labels: Performance, Refactor

#1387 Refactor `library/Mockery/CountValidator/*`
  library/Mockery/CountValidator/AtLeast.php
  library/Mockery/CountValidator/AtMost.php
  library/Mockery/CountValidator/CountValidatorAbstract.php
  library/Mockery/CountValidator/CountValidatorInterface.php
  library/Mockery/CountValidator/Exact.php
  library/Mockery/CountValidator/Exception.php
Labels: Performance, Refactor

#1390 Update `ReadTheDocs` dependencies
  docs/conf.py
  docs/requirements.txt
Labels: Documentation, patch, dependencies, Chore

#1393 Changelog v1.6.8
  CHANGELOG.md
Labels: patch, Changelog, Chore

#1357 Fix 8.3 get_parent_class without arguments deprecation
  tests/Mockery/RegExpCompatability.php
Labels: Tests, Chore

#1397 fix mock method $args parameter type
  library/Mockery.php
Labels: patch, Fixed

#1396 Fix `1.6.8` release
  .gitattributes
  e2e-test.sh
  library/Mockery/Exception/BadMethodCallException.php
  library/Mockery/Expectation.php
  library/Mockery/Mock.php
  psalm-baseline.xml
  tests/Mockery/ExpectationTest.php
Labels: Bug, Patch, Fixed

#1399 Changelog v1.6.10
  CHANGELOG.md
Labels: Patch, Changelog, Chore

#1401 Improve `Mockery::mock()` parameter type compatibility with array typehints
  library/Mockery.php
Labels: Patch, Fixed

#1403 Fix regression - partial construction with trait methods
  library/Mockery/Mock.php
  tests/Fixture/PHP74/Regression/Issue1402/InitTrait.php
  tests/Fixture/PHP74/Regression/Issue1402/Service.php
  tests/Unit/Regression/Issue1402Test.php
Labels: Patch, Fixed

#1406 Fix reserved words used to name a class, interface or trait
  library/Mockery.php
  library/Mockery/Reflector.php
  psalm-baseline.xml
  tests/Mockery/ReflectorTest.php
  tests/Unit/Regression/Issue1404Test.php
Labels: Patch, Fixed

#1407 Fix constants map generics doc comments
  library/Mockery/Configuration.php
Labels: Patch, Fixed

#1408 Changelog v1.6.11
  CHANGELOG.md
Labels: Patch, Changelog, Chore

#1409 Update CI workflows to test on PHP 8.4
  .github/workflows/codecov.yml
  .github/workflows/psalm.yml
  .github/workflows/tests.yml
Labels: Automation, Chore
