Repository mockery/mockery, pull requests merged in 2024-05, with the labels that each got.

#1417 Bump `Jinja2` from `3.1.3` to `3.1.4` fix CVE-2024-34064
  docs/requirements.txt
Labels: Documentation, Patch, Security

#1410 Fix PHP Doc Comments
  library/Mockery.php
  library/Mockery/Adapter/Phpunit/TestListenerTrait.php
  library/Mockery/Configuration.php
  library/Mockery/Container.php
  library/Mockery/CountValidator/AtLeast.php
  library/Mockery/CountValidator/AtMost.php
  library/Mockery/CountValidator/Exact.php
  library/Mockery/Exception/BadMethodCallException.php
  library/Mockery/Exception/InvalidCountException.php
  library/Mockery/Exception/InvalidOrderException.php
  library/Mockery/Exception/NoMatchingExpectationException.php
  library/Mockery/Expectation.php
  library/Mockery/ExpectsHigherOrderMessage.php
  library/Mockery/Generator/CachingGenerator.php
  library/Mockery/Generator/DefinedTargetClass.php
  library/Mockery/Generator/Method.php
  library/Mockery/Generator/MockConfiguration.php
  library/Mockery/Generator/MockConfigurationBuilder.php
  library/Mockery/Generator/MockDefinition.php
  library/Mockery/Generator/MockNameBuilder.php
  library/Mockery/Generator/Parameter.php
  library/Mockery/Generator/StringManipulation/Pass/AvoidMethodClashPass.php
  library/Mockery/Generator/StringManipulation/Pass/CallTypeHintPass.php
  library/Mockery/Generator/StringManipulation/Pass/ClassAttributesPass.php
  library/Mockery/Generator/StringManipulation/Pass/ClassNamePass.php
  library/Mockery/Generator/StringManipulation/Pass/ClassPass.php
  library/Mockery/Generator/StringManipulation/Pass/ConstantsPass.php
  library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php
  library/Mockery/Generator/StringManipulation/Pass/InterfacePass.php
  library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
  library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
  library/Mockery/Generator/StringManipulation/Pass/Pass.php
  library/Mockery/Generator/StringManipulation/Pass/RemoveBuiltinMethodsThatAreFinalPass.php
  library/Mockery/Generator/StringManipulation/Pass/RemoveDestructorPass.php
  library/Mockery/Generator/StringManipulation/Pass/RemoveUnserializeForInternalSerializableClassesPass.php
  library/Mockery/Generator/StringManipulation/Pass/TraitPass.php
  library/Mockery/Generator/StringManipulationGenerator.php
  library/Mockery/Generator/TargetClassInterface.php
  library/Mockery/Generator/UndefinedTargetClass.php
  library/Mockery/HigherOrderMessage.php
  library/Mockery/LegacyMockInterface.php
  library/Mockery/Loader/RequireLoader.php
  library/Mockery/Matcher/Subset.php
  library/Mockery/MethodCall.php
  library/Mockery/Mock.php
  library/Mockery/Undefined.php
  library/Mockery/VerificationDirector.php
  library/helpers.php
  phpunit.xml.dist
  psalm-baseline.xml
  psalm.xml.dist
  tests/Unit/PHP80/MockWithClosureAsLastArgumentTest.php
  tests/Unit/PHP81/Php81LanguageFeaturesTest.php
Labels: Patch, Fixed

#1419 Update e2e-test.sh
  e2e-test.sh
Labels: Patch, Chore

#1418 Changelog v1.6.12
  CHANGELOG.md
Labels: Patch, Changelog

#1424 Add test and fixture for PR #1423
  psalm-baseline.xml
  tests/Fixture/PHP74/DummyClass.php
  tests/Unit/PHP74/TestCase1132Test.php
Labels: Patch, Tests, Chore

#1428 Bump `requests` from 2.31.0 to 2.32.0
  docs/requirements.txt
Labels: Documentation, Patch, Security
