Repository mockery/mockery, pull requests merged in 2025-02, with the labels that each got.

#1451 Add `withAndOthers` expectation shorthand
  library/Mockery/Expectation.php
  tests/Unit/Mockery/ExpectationTest.php
Labels: Added

#1454 Fixed invalid variadic $args parameters
  CHANGELOG.md
  library/Mockery.php
Labels: Patch, Fixed

#1455 Bump jinja2 from 3.1.4 to 3.1.5
  docs/requirements.txt
Labels: Documentation, Patch, Security

#1456 Update composer dependencies
  composer.json
  composer.lock
Labels: Patch, dependencies

#1458 Update psalm baseline
  .github/workflows/psalm.yml
  psalm-baseline.xml
  psalm.xml.dist
Labels: Automation, Patch, Chore
